import { Button } from "@/components/ui/button";
import { ArrowRight, MessageCircle } from "lucide-react";
import { useSignIn } from "@clerk/clerk-react";

export default function Hero() {
  const { signIn } = useSignIn();

  const handleAuth = () => {
    signIn?.authenticateWithRedirect({
      strategy: "oauth_github",
      redirectUrl: "/sso-callback",
      redirectUrlComplete: "/new",
    });
  };
  return (
    <section className="pt-32 pb-20 md:pt-40 md:pb-28">
      <div className="container mx-auto px-4 sm:px-6 lg:px-8">
        <div className="max-w-4xl mx-auto text-center">
          <div>
            <div className="flex items-center justify-center mb-6">
              <span className="inline-block py-2 px-4 rounded-lg bg-yellow-100 text-yellow-800 text-sm font-medium border border-yellow-200">
                🚧 Early alpha - looking for feedback
              </span>
            </div>
            <h1 className="text-4xl md:text-5xl lg:text-6xl font-bold leading-tight mb-6 text-neutral-900">
              Generate docs for your AI coding tools
            </h1>
            <p className="text-lg md:text-xl text-neutral-600 mb-8 max-w-3xl mx-auto">
              A tool to create technical documentation from your codebase. Saves
              time vs. writing by hand, produces better output because our AI
              agent actually reads your code.
            </p>
            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <Button
                className="bg-[#1B9847] hover:bg-[#158039] text-white text-lg px-8 py-6 h-auto"
                onClick={handleAuth}
              >
                Try it free
                <ArrowRight className="ml-2 h-5 w-5" />
              </Button>
              <Button variant="outline" className="text-lg px-8 py-6 h-auto">
                <MessageCircle className="mr-2 h-5 w-5" />
                <a href="mailto:chris.wood@qckfx.com" className="text-inherit">
                  Give feedback
                </a>
              </Button>
            </div>
            <div className="mt-8 text-sm text-neutral-500">
              Generate .cursorrules, TaskMaster PRDs, ADRs • Edit in browser •
              Export as .md
            </div>
          </div>

          <div className="mt-16 relative">
            <div className="bg-white rounded-lg shadow-lg border border-neutral-200 p-6 max-w-2xl mx-auto">
              <div className="text-left">
                <div className="flex items-center mb-4">
                  <div className="w-3 h-3 bg-red-500 rounded-full mr-2"></div>
                  <div className="w-3 h-3 bg-yellow-500 rounded-full mr-2"></div>
                  <div className="w-3 h-3 bg-green-500 rounded-full mr-2"></div>
                  <span className="text-sm text-neutral-500 ml-2">
                    compose-editor.md
                  </span>
                </div>
                <div className="space-y-3 text-sm text-neutral-700">
                  <p className="font-semibold">
                    # Architecture Decision Record: Database Query Patterns
                  </p>
                  <p>## Status</p>
                  <p>Accepted</p>
                  <p>## Context</p>
                  <p>
                    Our codebase uses Prisma ORM with PostgreSQL. Analysis shows
                    inconsistent query patterns across the application...
                  </p>
                  <p>## Decision</p>
                  <p>
                    We will standardize on repository pattern with service layer
                    for all database operations to improve maintainability...
                  </p>
                  <div className="bg-green-50 border-l-4 border-green-400 p-3 mt-4">
                    <p className="text-green-800 text-xs">
                      ✓ Generated by reading your actual code patterns
                    </p>
                  </div>
                </div>
              </div>
            </div>
            <div className="absolute -bottom-4 -right-4 bg-blue-100 border border-blue-200 rounded-lg p-3 text-sm text-blue-800 max-w-xs">
              <p className="font-medium">Edit in browser</p>
              <p className="text-xs mt-1">Then export or copy to clipboard</p>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
